apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: istio-ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: technical@mydomain.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # No selector, match all domains by default.
    - http01:
        ingress:
          class: istio