apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-alertmanager
  namespace: prometheus-stack
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  azureFile:
    secretName: azurefile-secret
    secretNamespace: prometheus-stack
    shareName: alertmanager
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
