apiVersion: v1
kind: Secret
metadata:
  name: azurefile-secret
  namespace: prometheus-stack
type: Opaque
data:
  azurestorageaccountname: {{ required "A valid Storage Account name is required!" .Values.storage.name }}
  azurestorageaccountkey: {{ required "A valid Storage Account key is required!" .Values.storage.key }}