# Verify that all needed variables are set.
- name: "Verifying the existence of all needed variables."
  assert:
    that:
      - istio_kubectl_config is defined
      - istio_configuration_project_dir is defined
      - istio_configuration_file_name is defined
      - istio_loadbalancer_ip_resource_group is defined
      - istio_loadbalancer_ip is defined
      - istio_loadbalancer_dns is defined

# Install the istio-operator controller.
- name: "Installing the istio-operator controller."
  shell: "istioctl operator init -c {{ istio_kubectl_config }}"
  
# Create the istio-system namespace.
- name: "Creating the egressgateway namespace."
  k8s:
    src : "{{ istio_configuration_project_dir }}/namespace_istiosystem.yaml"
    kubeconfig: "{{ istio_kubectl_config }}"
    state: present

# Create the istio ingressgateway namespace.
- name: "Creating the ingressgateway namespace."
  k8s:
    src : "{{ istio_configuration_project_dir }}/namespace_ingressgateway.yaml"
    kubeconfig: "{{ istio_kubectl_config }}"
    state: present

# Create the istio egressgateway namespace.
- name: "Creating the egressgateway namespace."
  k8s:
    src : "{{ istio_configuration_project_dir }}/namespace_egressgateway.yaml"
    kubeconfig: "{{ istio_kubectl_config }}"
    state: present

# Restrict access to the istio-operator controller via a network policy.
- name: "Creating the istio-operator network policy."
  k8s:
    src : "{{ istio_configuration_project_dir }}/networkpolicy_denyall.yaml"
    kubeconfig: "{{ istio_kubectl_config }}"
    state: present

# Copy the file in order to replace placeholders in it.
- name: "Making a changeable copy of the istio configuration."
  copy:
    src: "{{ istio_configuration_project_dir }}/istiooperator_istiosystem.yaml"
    dest: "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"

# Replace: $IP_RESOURCEGROUP with terraform value.
- name: "Replacing placeholder '$IP_RESOURCEGROUP' with the resource group name for the general resources."
  replace:
    path: "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"
    regexp: '\$IP_RESOURCEGROUP'
    replace: '{{ istio_loadbalancer_ip_resource_group }}'

# Replace: $LOADBALANCER_IP with terraform value.
- name: "Replacing placeholder '$LOADBALANCER_IP' with the external cluster ip."
  replace:
    path: "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"
    regexp: '\$LOADBALANCER_IP'
    replace: '{{ istio_loadbalancer_ip }}'

# Replace: $LOADBALANCER_DNS with terraform value.
- name: "Replacing placeholder '$LOADBALANCER_DNS' with the external cluster dns."
  replace:
    path: "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"
    regexp: '\$LOADBALANCER_DNS'
    replace: '{{ istio_loadbalancer_dns }}'

# Add the istio-operator.
- name: "Creating the istio-operator."
  k8s:
    src : "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"
    kubeconfig: "{{ istio_kubectl_config }}"
    state: present

# Enforce mutual tls in istio.
- name: "Enforcing mutual tls in istio."
  k8s:
    src : "{{ istio_project_dir }}/peerauthentication_mutualtls.yaml"
    kubeconfig: "{{ kubectl_config }}"
    state: present
  register: istio_mututal_tls_result
  retries: 25
  delay: 10
  until: istio_mututal_tls_result.failed == false

# ----- Notes: -----
# - "\t"s do NOT work!
# - When using the blacklist, the namespace must also be marked with the istio
#   injection flag.
# The istio config map injection key can be disabled here.
# See:
# https://github.com/istio/istio/issues/6476#issuecomment-399219937
# By setting the selector entries pods in a marked namespace can be excluded 
# from the injection.
- name: "Copying injection config map."
  shell: kubectl get cm istio-sidecar-injector -n istio-system -o yaml > istio-sidecar-injector.temp.yaml
  environment:
    KUBECONFIG: "{{ istio_kubectl_config }}"
- name: "Replacing injection selection keys."
  replace:
    path: "istio-sidecar-injector.temp.yaml"
    before: injectedAnnotations
    after: neverInjectSelector
    regexp: '\[\]'
    replace: |-
      - matchLabels:
                app: kube-prometheus-stack-admission-create
            - matchLabels:
                app: kube-prometheus-stack-admission-patch
            - matchLabels:
                app.kubernetes.io/name: kube-state-metrics
            - matchLabels:
                app: kube-prometheus-stack-operator
            - matchLabels:
                app: prometheus-node-exporter
            - matchLabels:
                app.kubernetes.io/name: grafana
            - matchLabels:
                app: alertmanager
- name: "Uploading the changed injection config map."
  k8s:
    src : "istio-sidecar-injector.temp.yaml"
    kubeconfig: "{{ istio_kubectl_config }}"
    state: present

# Add a default http gateway.
- name: "Adding a default http gateway."
  k8s:
    src : "{{ istio_project_dir }}/gateway_httpdefault.yaml"
    kubeconfig: "{{ istio_kubectl_config }}"
    state: present