# Verify that all needed variables are set.
- name: "Verifying the existence of all needed variables."
  assert:
    that:
      - istio_configuration_project_dir is defined
      - istio_configuration_file_name is defined
      - loadbalancer_ip_resource_group is defined
      - loadbalancer_ip is defined
      - loadbalancer_dns is defined
    
# Copy the file in order to replace placeholders in it.
- name: "Making a changeable copy of the istio configuration."
  copy:
    src: "{{ istio_configuration_project_dir }}/istiooperator_configuration.yaml"
    dest: "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"

# Replace: $IP_RESOURCEGROUP with terraform value.
- name: "Replacing placeholder '$IP_RESOURCEGROUP' with the resource group name for the general resources."
  replace:
    path: "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"
    regexp: '\$IP_RESOURCEGROUP'
    replace: '{{ loadbalancer_ip_resource_group }}'

# Replace: $LOADBALANCER_IP with terraform value.
- name: "Replacing placeholder '$LOADBALANCER_IP' with the external cluster ip."
  replace:
    path: "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"
    regexp: '\$LOADBALANCER_IP'
    replace: '{{ loadbalancer_ip }}'

# Replace: $LOADBALANCER_DNS with terraform value.
- name: "Replacing placeholder '$LOADBALANCER_DNS' with the external cluster dns."
  replace:
    path: "{{ istio_configuration_project_dir }}/{{ istio_configuration_file_name }}"
    regexp: '\$LOADBALANCER_DNS'
    replace: '{{ loadbalancer_dns }}'