# Verify that all needed variables are set.
- name: "Verifying the existence of all needed variables."
  assert:
    that:
      - prometheus_kubectl_config is defined
      - prometheus_configuration_project_dir is defined
      - prometheus_storage_account_name is defined
      - prometheus_storage_account_key is defined
      - prometheus_grafana_admin_password is defined
      - prometheus_version is defined

# Use helm to template the configuration.
- name: "Templating the configuration files."
  vars:
    folderpath: "{{ prometheus_configuration_project_dir }}/helm/preparation-resources"
  shell: > 
    helm template {{ folderpath }} 
    --set storage.name={{ prometheus_storage_account_name | b64encode }} 
    --set storage.key={{ prometheus_storage_account_key | b64encode }} 
    > {{ folderpath }}/template-result.temp.yaml

# Apply the created configuration file to the cluster.
- name: "Applying the created template to the cluster."
  k8s:
    src : "{{ prometheus_configuration_project_dir }}/helm/preparation-resources/template-result.temp.yaml"
    kubeconfig: "{{ prometheus_kubectl_config }}"
    state: present

# Add the prometheus community repo.
- name: "Adding the 'promethues community' repo to list of known ones."
  shell: "helm repo add prometheus-community https://prometheus-community.github.io/helm-charts"

# Add the stable repo (should already be present).
- name: "Adding the 'stable' repo to list of known ones."
  shell: "helm repo add stable https://charts.helm.sh/stable"

# Update the repos.
- name: "Updating repos."
  shell: "helm repo update"

# Install the helm chart.
- name: "Installing the prometheus-stack."
  environment:
    KUBECONFIG: "{{ prometheus_kubectl_config }}"
  shell: >
    helm install prometheus-stack 
    --namespace prometheus-stack 
    --values {{ prometheus_configuration_project_dir }}/helm/installation-resources/values.yaml 
    --set grafana.adminPassword={{ prometheus_grafana_admin_password }}
    prometheus-community/kube-prometheus-stack 
    --version="{{ prometheus_version }}"