apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    egressGateways:
      - enabled: true
        namespace: istio-egress
        name: istio-egressgateway
    ingressGateways:
      - enabled: true
        namespace: istio-ingress
        name: istio-ingressgateway
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-resource-group: $IP_RESOURCEGROUP
            # Add the dns name to the azure ip resource. This adds ".<region>.cloudapp.azure.com" 
            # to the value provided here.
            service.beta.kubernetes.io/azure-dns-label-name: $LOADBALANCER_DNS
          service:
            loadBalancerIP: $LOADBALANCER_IP
  meshConfig:
    # Do not allow the sidecar to send traffic to external sources 
    # unless they are defined in the service mesh.
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    # Enable logging for the sidecars.
    accessLogFile: "/dev/stdout"
    # JSON or TEXT as logging encoding.
    accessLogEncoding: TEXT
    # Do not merge the envoy metrics with the application ones. Requires the scraper to
    # use mtls when accessing the application metrics. Envoy ones are exposed in plain text.
    enablePrometheusMerge: false