# Deny all ingress by default.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: istio-operator
spec:
  podSelector: {}
  policyTypes:
  - Ingress