apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    # Enforce mutual tls per default in all workloads.
    mode: STRICT